### ISSUE TITLE
Design Source Files

### ISSUE THREAD

**Issue by Herbstlied** [ncase/polygons#16]
We are working on an Arabic translation and it would be helpful if we can get our hands on the source design files (SVG, PSD, ...). That would make the resulting images as identical as possible to the original ones.

Thanks!

**Comment by sortingbubbles** [comment]
maybe this will help https://github.com/ncase/polygons/pull/14

**Comment by ncase** [comment]
How have I not even seen that image translator tool. I am seriously not good at staying on top of my git repo, wow. Thanks @sortingbubbles! And yes @Herbstlied, use the image translator tool, and also thank you for wanting to do the Arabic translation!

(For my next playable posts, and hopefully there's a new one next month, the translation process will be MUCH simpler.)

**Comment by codefrau** [comment]
Yep. I made that for the German buttons, because I'm much better with code than photoshop. 
Here's the translator version drawing the German images:
http://ncase.me/polygons-de/translator/translator.html
That's on _your_ website, @ncase ;)

**Comment by sortingbubbles** [comment]
No problem @ncase! 
My team is working on the Greek translation and we'll definitely use your very useful Image Translator @bertfreudenberg!

**Comment by Herbstlied** [comment]
Thank you all for your input. We are using the image translator now.

@ncase, if you could merge #14, for everyone who may want to contribute a translation in the future. Looking forward to the upcoming playables!
