### ISSUE TITLE
Ada initiative is now closed; Remove from Page?

### ISSUE THREAD

**Issue by jackiekazil** [ncase/polygons#21]
Ada initiative is now closed
Maybe it should be removed from the page?

**Comment by brendacs** [comment]
It might be fine to leave it on the page since the Ada Initiative's website now shows ways to continue their work through a lot of other events and organizations.

**Comment by puzzlement** [comment]
I was an Ada Initiative co-founder. I've sent a PR to remove it from the page: https://github.com/ncase/polygons/pull/29

If you want to keep it in some form as a source of resources, that would be fine, but having it under the donate heading probably isn't the right place.

**Comment by ncase** [comment]
Ah, this slipped my mind! Thanks for making the PR, I just pulled it. Sad to hear Ada Initiative's closed, but it's still great work that they did, while they were still around
