### ISSUE TITLE
Pull request guidelines?

### ISSUE THREAD

**Issue by Guillawme** [ncase/polygons#22]
Hello there,

I would like to contribute some minor revisions to the French translation. Before I start, I need to know how to contribute: which branch should I commit my changes to? (`gh-pages`? `master`? a new branch?).

Thanks in advance.

**Comment by ncase** [comment]
Thank you for helping! :) Actually, you should commit to the gh-pages of _this_ repository: https://github.com/ncase/polygons-fr (it's /polygons-fr instead of /polygons)

**Comment by Guillawme** [comment]
OK, thank you.
