### ISSUE TITLE
Add Russian translation

### ISSUE THREAD

**Issue by unkaktus** [ncase/polygons#23]
Hi @ncase,
I've made a translation of polygons into Russian. Live version can be found here: https://nogoegst.github.io/polygons-ru/
The repo can be found here: https://github.com/nogoegst/polygons-ru
Thanks!

**Comment by ncase** [comment]
Thank you so much! :D I've added a link to your Russian version on [the main Polygons page](http://ncase.me/polygons/).

Ta-dah:
<img width="439" alt="screen shot 2016-08-23 at 17 07 14" src="https://cloud.githubusercontent.com/assets/825858/17909805/23a45f60-6954-11e6-972f-60d9edca2398.png">
