### ISSUE TITLE
playable page is down

### ISSUE THREAD

**Issue by alan-isaac** [ncase/polygons#25]
The project page https://github.com/ncase/polygons links to the playable page http://ncase.me/polygons, but the latter has been unresponsive for some time now.

**Comment by Deledrius** [comment]
The main site appears to be up and working for me.

**Comment by alan-isaac** [comment]
You are correct; I see it now, but I had to disconnect from my universities VPN to do so.  Thanks.

**Comment by strugee** [comment]
I guess this issue can be closed then?

**Comment by alan-isaac** [comment]
I agree it can be closed.  I'll still try to learn why this is happening and post here just for the informational value if I can figure it out.
