### ISSUE TITLE
Left side graph not showing up when accessing from local storage

### ISSUE THREAD

**Issue by BTCafe** [ncase/polygons#28]
The right graph however loaded up nicely. Is there something i miss in order to view it locally ? 
I only have Apache active at the time.

Here's the screenshot of it just in case
![index2](https://cloud.githubusercontent.com/assets/24642717/22627319/8f95ead2-ebf3-11e6-86e4-993bbda35478.PNG)
![index1](https://cloud.githubusercontent.com/assets/24642717/22627320/8f9a573e-ebf3-11e6-9887-3d07031e5eda.PNG)

**Comment by ncase** [comment]
Hi @Naufal-FR!  The simulations load its images through AJAX, but apparently Chrome doesn't like doing AJAX on "file://" urls.  It complains that it's "cross domain" or something.

The way to fix this is to run it on a local server!  If you're on Unix/Linux/Mac, [you can do this through the terminal](https://css-tricks.com/snippets/html/start-a-web-server-with-one-terminal-command-on-os-x/), and if you're on Windows, [you can install and run WAMP](http://www.wampserver.com/en/).  Best of luck!

**Comment by BTCafe** [comment]
Hello too @ncase 
I tried running it on local server (forgot AJAX has that limitation) and it kinda fix the problem albeit only on all of the "chapter" and one "playable" simulation. The first "playable" simulation showed up normally but the rest of them still blank.

> One of the simulation from "Chapter"
![work3](https://cloud.githubusercontent.com/assets/24642717/22765541/79928ba2-eea3-11e6-9191-7453192d4f53.PNG)

> First "Playable" Simulation
![work1](https://cloud.githubusercontent.com/assets/24642717/22765539/797079fe-eea3-11e6-80c1-430476df4e5e.PNG)

> Second "Playable" Simulation (same thing with the rest of them)
![work2](https://cloud.githubusercontent.com/assets/24642717/22765540/79780e12-eea3-11e6-8ab6-0e6b5ad6a2b9.PNG)

I'm using XAMPP at the moment since it's already installed on my computer if that helps. 

Btw, is it possible the problem lies in Visual C++ version ? WAMP is kinda hard to install because all of the VC version required to install it so maybe that's the reason why you recommend it ?

**Comment by ncase** [comment]
Hm... that's strange.  I see that the URL is `localhost/Polygons/index.html` -- maybe try running the server *from* `/Polygons`, so that the URL is just `localhost/index.html` or `localhost`?

If that still doesn't work, what does error does the Javascript console say?

**Comment by BTCafe** [comment]
I tried copying the inside of Polygons folder outside but the result is still the same as the last one
![try1](https://cloud.githubusercontent.com/assets/24642717/22849952/39373a42-f035-11e6-9efa-178d41af819c.jpg)

As for the terminal, there's a few error happening but it's mainly about the `requestAnimFrame`
![try2](https://cloud.githubusercontent.com/assets/24642717/22849964/5c4474d2-f035-11e6-950b-8b849aa37d7f.PNG)

**Comment by ncase** [comment]
That's really weird. Could you check the very bottom of `automatic.js`? There should be this code which defines `requestAnimFrame`:

    ////////////////////
    // ANIMATION LOOP //
    ////////////////////
    window.requestAnimFrame = window.requestAnimationFrame ||
    	window.webkitRequestAnimationFrame ||
    	window.mozRequestAnimationFrame ||
    	function(callback){ window.setTimeout(callback, 1000/60); };

If that code's not there, re-download `automatic.js` here: https://raw.githubusercontent.com/ncase/polygons/gh-pages/play/automatic/automatic.js

**Comment by BTCafe** [comment]
Finally it works ~
I don't know how but for some reason the code of `window.requestAnimFrame` changed into `window.requestAnimatiFrame` . Really strange because i don't remember making any changes to that part ...

Anyway, thank you for the support. Will close this one now.

**Comment by ncase** [comment]
How bizarre! But I'm glad to hear it works now. :)
