### ISSUE TITLE
Persian Translation done

### ISSUE THREAD

**Issue by hamed** [ncase/polygons#32]
hamed.github.io/polygons/
فارسی

**Comment by ncase** [comment]
Oh, sweet! Thank you so much, I've added it to the main site!

![image](https://user-images.githubusercontent.com/825858/30728016-15776f94-9f23-11e7-8f74-b7d7fcac41e2.png)

P.S: love the font you chose!

**Comment by hamed** [comment]
Thanks! I will take a break and start the next!
