### ISSUE TITLE
Typo in russian translation

### ISSUE THREAD

**Issue by ikacnep** [ncase/polygons#36]
The word "playable" should be "играбельный", not "играбелный" (note the 4-th letter from end --- 'ь'). It is spelled incorrectly both in title and footer.

I've failed to find translations source :( otherwise I'd fix it myself

**Comment by ncase** [comment]
Thank you @ikacnep !  (Sorry for the late reply, was taking a break)  The source repo for the Russian translation is _not_ owned by me either, actually.  It belongs to @nogoegst, here: https://github.com/nogoegst/polygons-ru/  Let them know, and thanks again!

**Comment by ikacnep** [comment]
Ok, thank you, I'll PR there :)
